-- Tabla de perfiles para extender los datos de auth.users
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role TEXT DEFAULT 'admin' CHECK (role IN ('admin', 'superadmin')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad
DROP POLICY IF EXISTS "Admins pueden ver todos los perfiles" ON public.profiles;
CREATE POLICY "Admins pueden ver todos los perfiles" 
ON public.profiles FOR SELECT 
TO authenticated 
USING ( true );

DROP POLICY IF EXISTS "Superadmins pueden gestionar perfiles" ON public.profiles;
CREATE POLICY "Superadmins pueden gestionar perfiles" 
ON public.profiles FOR ALL 
TO authenticated 
USING ( (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'superadmin' );

-- Trigger para crear perfil automáticamente al registro
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'admin');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- TABLA DE SERVICIOS
CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  icon_name TEXT DEFAULT 'Cpu',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- TABLA DE PLANES (PRECIOS)
CREATE TABLE IF NOT EXISTS public.plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  description TEXT,
  features JSONB DEFAULT '[]'::jsonb,
  is_popular BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- TABLA DE PROMOCIONES
CREATE TABLE IF NOT EXISTS public.promotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  code TEXT,
  expiry_date DATE,
  icon_name TEXT DEFAULT 'Gift',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- TABLA DE NOTICIAS (POSTS)
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Tecnología',
  status TEXT DEFAULT 'Publicado',
  content TEXT,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS en las nuevas tablas
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura pública (cualquiera puede ver)
DROP POLICY IF EXISTS "Servicios visibles para todos" ON public.services;
CREATE POLICY "Servicios visibles para todos" ON public.services FOR SELECT USING (true);

DROP POLICY IF EXISTS "Planes visibles para todos" ON public.plans;
CREATE POLICY "Planes visibles para todos" ON public.plans FOR SELECT USING (true);

DROP POLICY IF EXISTS "Promociones visibles para todos" ON public.promotions;
CREATE POLICY "Promociones visibles para todos" ON public.promotions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Noticias visibles para todos" ON public.posts;
CREATE POLICY "Noticias visibles para todos" ON public.posts FOR SELECT USING (true);

-- Políticas de edición solo para admins
DROP POLICY IF EXISTS "Solo admins gestionan servicios" ON public.services;
CREATE POLICY "Solo admins gestionan servicios" ON public.services FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Solo admins gestionan planes" ON public.plans;
CREATE POLICY "Solo admins gestionan planes" ON public.plans FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Solo admins gestionan promociones" ON public.promotions;
CREATE POLICY "Solo admins gestionan promociones" ON public.promotions FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Solo admins gestionan noticias" ON public.posts;
CREATE POLICY "Solo admins gestionan noticias" ON public.posts FOR ALL TO authenticated USING (true);

-- DATOS INICIALES DE EJEMPLO
INSERT INTO public.services (name, description, icon_name) VALUES
('Sistemas Web', 'Plataformas escalables con React y arquitecturas distribuidas.', 'Monitor'),
('Apps Móviles', 'Experiencias nativas y cross-platform de alto rendimiento.', 'Smartphone'),
('Big Data & AI', 'Analítica predictiva e integración de modelos LLM.', 'Database');

INSERT INTO public.plans (name, price, description, features, is_popular) VALUES
('Starter', 999000, 'Ideal para startups en fase inicial.', '["Landing Page Animada", "SEO Básico", "Soporte 1 mes"]', false),
('Pro', 2499000, 'Para empresas en crecimiento constante.', '["E-commerce Full", "CMS Personalizado", "Integración IA"]', true),
('Enterprise', 4999000, 'Soluciones a medida para grandes corporaciones.', '["Seguridad Avanzada", "SLA 99.9%", "Soporte 24/7"]', false);

INSERT INTO public.promotions (title, description, code, expiry_date, icon_name) VALUES
('Descuento Early Adopter', '20% de descuento en tu primer proyecto.', 'FUTURA20', '2026-12-31', 'Gift'),
('Auditoría Gratuita', 'Análisis de seguridad sin costo.', 'FREEAUDIT', '2026-12-31', 'Zap');

-- TABLA DE GORRAS (CROWN & CAP) - PERSISTENTE EN LA NUBE
CREATE TABLE IF NOT EXISTS public.gorras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT DEFAULT '',
  precio NUMERIC NOT NULL,
  color TEXT NOT NULL,
  categoria TEXT NOT NULL,
  estilo TEXT NOT NULL,
  imagen_url TEXT NOT NULL,
  imagenes JSONB DEFAULT '[]'::jsonb,
  destacada INTEGER DEFAULT 0,
  stock INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Políticas RLS para Gorras
ALTER TABLE public.gorras ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Gorras visibles para todos" ON public.gorras;
CREATE POLICY "Gorras visibles para todos" ON public.gorras FOR SELECT USING (true);

DROP POLICY IF EXISTS "Gorras insertables" ON public.gorras;
CREATE POLICY "Gorras insertables" ON public.gorras FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Gorras actualizables" ON public.gorras;
CREATE POLICY "Gorras actualizables" ON public.gorras FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Gorras eliminables" ON public.gorras;
CREATE POLICY "Gorras eliminables" ON public.gorras FOR DELETE USING (true);

-- TABLA DE CONFIGURACION GENERAL TIENDA
CREATE TABLE IF NOT EXISTS public.configuracion (
  clave TEXT PRIMARY KEY,
  valor TEXT NOT NULL
);

ALTER TABLE public.configuracion ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Configuracion visible para todos" ON public.configuracion;
CREATE POLICY "Configuracion visible para todos" ON public.configuracion FOR SELECT USING (true);

DROP POLICY IF EXISTS "Configuracion editable" ON public.configuracion;
CREATE POLICY "Configuracion editable" ON public.configuracion FOR ALL USING (true);

INSERT INTO public.configuracion (clave, valor) VALUES 
('whatsapp_phone', '573502522375'),
('nombre_tienda', 'CROWN & CAP COLOMBIA')
ON CONFLICT (clave) DO NOTHING;

